@devUrl=localhost:9090
@apiV1=/api/v1

GET {{apiV1}}/nikaya/truongbokinh
Host: {{devUrl}}
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE1MjM5MjYsImlzcyI6Iklzc3Vlci1UZXN0Iiwic3ViIjoiaGVsbG8ifQ.Y0g7QTjZMufykWoyjWf_TW1YTtEa73j9Hume2B60PPDqCZhiXa6HUCiBqAMN6GAr6H1mAz0X-k-MA043ASyvmaTQn9hG60xe-v8Y1DLY8tytCdMMNgqV1A9UpmdtVgcdNP0ZBzpMCXU7QJRzz0YBTxpzJIJLPHgmpdvLKVao4j8




###
POST {{apiV1}}/auth/token
Host: {{devUrl}}
Content-Type: application/json

{}

### Get List
GET {{apiV1}}/user/list
Host: {{devUrl}}
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE2NzE0NzYsImlzcyI6Iklzc3Vlci1UZXN0Iiwic3ViIjoiaGVsbG8ifQ.ioC9RxaC6Hkdm1f0T1rF5XjDiwnv487Cp_ovmtR81wP59LZ0EwD3aE-g9v9MRcHmI93ywvfK_AFFWNWSvxYL_2YIw40CCfCCEWMg_bgXrCoIFDcVdfXfvhXGYxabwjIVlNlwv6TivwHTXj66MeCbEoHCVEU4CLj-Oo3SUpqTOuY

### Get By Id
GET {{apiV1}}/users/5
Host: {{devUrl}}
Content-Type: application/json

### Create
POST {{apiV1}}/user/create
Host: {{devUrl}}
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE2NzE0NzYsImlzcyI6Iklzc3Vlci1UZXN0Iiwic3ViIjoiaGVsbG8ifQ.ioC9RxaC6Hkdm1f0T1rF5XjDiwnv487Cp_ovmtR81wP59LZ0EwD3aE-g9v9MRcHmI93ywvfK_AFFWNWSvxYL_2YIw40CCfCCEWMg_bgXrCoIFDcVdfXfvhXGYxabwjIVlNlwv6TivwHTXj66MeCbEoHCVEU4CLj-Oo3SUpqTOuY

{
  "name":"KhaBD",
  "age": 21,
  "address": {
    "state": "Ho Chi Minh",
    "city": "Ho Chi Minh City",
    "pincode": 700000
  }
}
